name: Build and push pipeline-run-docker image

on:
  push:
    branches:
      - "master"
      - "artifact-migration-25q3"
    paths:
      - "pipeline/build-pipeline-docker-images/pipeline-run-docker/**"
      - "pipeline/build-pipeline-docker-images/build.sh"
      - ".github/workflows/build_pipeline_docker.yml"

env:
  ARTIFACT_REGISTRY_REPO: us-central1-docker.pkg.dev/depmap-consortium/depmap-docker-images/depmap-pipeline-run
  DOCKER_TAG: ga2-build-${{ github.run_number }}
  DOCKERFILE_DIR: pipeline-run-docker

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Artifact Registry
        uses: docker/login-action@v2
        with:
          registry: us-central1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.DEPMAP_DEPLOY_SVC_ACCT }}
      - name: Build and push depmap pipeline docker image
        run: cd pipeline/build-pipeline-docker-images && bash build.sh ${{ env.ARTIFACT_REGISTRY_REPO }} ${{ env.DOCKER_TAG }} ${{ env.DOCKERFILE_DIR }}
      - name: Tag and push to Artifact Registry
        run: |
          docker tag ${{ env.ARTIFACT_REGISTRY_REPO }}:${{ env.DOCKER_TAG }} ${{ env.ARTIFACT_REGISTRY_REPO }}:latest
          docker push ${{ env.ARTIFACT_REGISTRY_REPO }}:latest
